name: doc_scanner_ios
description: iOS native camera document scanner plugin for iSmart Messenger
version: 0.0.1
publish_to: "none"

environment:
  sdk: ^3.9.2
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: DocScannerIosPlugin
