// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1uTDfajiiP43cvIaV8D80RW_lv4_Rvd0',
    appId: '1:1039491251685:web:8906f28f59e78394fec30c',
    messagingSenderId: '1039491251685',
    projectId: 'ismart-messenger',
    authDomain: 'ismart-messenger.firebaseapp.com',
    storageBucket: 'ismart-messenger.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmxTyxp3Gpvr55_1AHWUKubnPrJmKbh9c',
    appId: '1:1039491251685:android:c2b94de86bd35164fec30c',
    messagingSenderId: '1039491251685',
    projectId: 'ismart-messenger',
    storageBucket: 'ismart-messenger.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnlCaXzG4fQ2RkWoCY7vUjG5E_5xmFE-U',
    appId: '1:1039491251685:ios:a82afb4bb1054745fec30c',
    messagingSenderId: '1039491251685',
    projectId: 'ismart-messenger',
    storageBucket: 'ismart-messenger.firebasestorage.app',
    iosBundleId: 'com.simplesplashview.mobile.app',
  );
}
